frame.background=#FFFFFF
frame.foreground=#2B2B2B
panel.background=#FFFFFF
panel.foreground=#2B2B2B
button.background=#808080
button.foreground=#FFFFFF
isDark=false
login.time=null
login.ID=null
login.name=null
login.grade=null